# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SS6xebX7QOaLHshWZpJ7Qrnj6ugfEwfb
"""

print("Welcome to the customer service analyzer!")
import json, nltk, requests, textblob
nltk.download("punkt")
nltk.download("averaged_perceptron_tagger")
numbers = []
repeat = "yes"

while repeat.lower().strip() == "yes":

    response = requests.get("https://dgoldberg.sdsu.edu/515/customer_service_tweets_full.json")
    peroform = input("Which analysis would you like to peroform (polarity/subjectivity/formality)?").lower().strip()

    if peroform == "polarity":
        search = input("Which Twitter handle would you lie to analyze?").lower().strip()
        data = json.loads(response.text)
        text = ""
        a = 0
        b = 0
        for line in data:
            company = line["Company"]
            review = line["Text"]
            text = text + company + review + " "
            blob = textblob.TextBlob(text)

            numbers.append(blob.polarity)

            a = len(numbers)
            b = sum(numbers)
            ave = b/a
        print(search,":",ave)
    elif peroform == "subjectivity":
        search = input("Which Twitter handle would you lie to analyze?").lower().strip()        
        data = json.load(response.text)
        text = ""
        a = 0
        b = 0
        for line in data:
            company = ["Company"]
            review= line["Text"]
            text = text + company + review + " "
            blob = textblob.TextBlob(text)

            numbers.append(blob.subjectivity)
            a = len(numbers)
            b = sum(numbers)
            ave = b/a
        print(search, ":",ave)       

    elif peroform == "formality":
        serach = input("Which Twitter handle would you lie to analyze?").lower().strip()
        data = json.load(response.text)
        text = ""

        data = json.load(response)
        for line in data:
            company = ["Company"]
            review= line["Text"]
            text = text + company + review + " "
            blob = textblob.TextBlob(text)

        f = 0
        c = 0
        for word, tag in blob.tag:
            if "NN"in tag:
                f = f + 1
            if "PR" in tag:
                c = c + 1
            z = (50 * ((f-c)/(f+c)+1))
        print(search, ":", z)

    else:
        print("Sorry, that type of analysis is not supported. Please try again.")
repeat = ("Would you like to run another analysis (yes/no)? ")